config/routes.rb
Onetomanyassociation::Application.routes.draw do
  resources :schools do
    resources :students
  end

   root :to => 'schools#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_accessible :avatar
	mount_uploader :avatar, AvatarUploader
	belongs_to :student
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :school
	has_one :photo
	accepts_nested_attributes_for :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @school = School.find(params[:school_id])
    @students = @school.students.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
     @school = School.find(params[:school_id])
    @student = @school.students.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new

    @school = School.find(params[:school_id])
    @student = @school.students.build
    @photo = @student.build_photo
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
     @school = School.find(params[:school_id])
     @student = @school.students.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create

    @school = School.find(params[:school_id])
    @student = @school.students.build(params[:student])
    respond_to do |format|
      if @student.save
        format.html { redirect_to ([@school, @student]), notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @school = School.find(params[:school_id])
    @student = @school.students.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to ([@school, @student]), notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onetomanyassociation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>All Students with Schools Hyderabad>>>>>>>>>>>>>   </h1>
<table>
  <tr>
    <th>School address area</th>
    <th>Student Name with full</th>
    <th>Student Age</th>
    <th></th>
  </tr>

<% @schools.each do |school| %>
<% school.students.each do |student| %>
  <tr>
    <td><%= school.address %></td>
    <td><%= student.name %></td>
    <td><%= student.age %></td>
    <td></td>
  </tr>
  <% end %>
<% end %>
</table>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @school.address %>
</p>


<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %> |
<%= link_to 'new student',  new_school_student_path(@school) %>

app/views/students/_form.html.erb
<%= semantic_form_for([@school, @student]) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name %>
  </div>
  <div class="field">
    <%= f.input :age %>
  </div>
  <%= f.fields_for :photo, :multipart => true do |f| %>
    <div class="field">
    <%= f.file_field :avatar %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', school_student_path(@school, @student) %> |
<%= link_to 'Back', school_students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.age %></td>
    <td><%= link_to 'Show', school_student_path(@school, student) %></td>
    <td><%= link_to 'Edit', edit_school_student_path(@school, student) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_school_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back',  school_students_path(@school) %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Age:</b>
  <%= @student.age %>
</p>

<p>
	<b>Photo</b>
<%= image_tag(@student.photo.avatar_url)  %>
</p>


<%= link_to 'Edit', edit_school_student_path(@school, @student) %> |
<%= link_to 'Back', school_students_path %>